import calendar
from tkinter import *
from tkinter import messagebox,ttk

class Calender:
    def __init__(self,master):
        self.frame = Frame(master)

        button = Button(self.frame, text = 'What year and month?', command = self.open)
        button.pack(padx=50, pady=20)


        self.frame.pack(padx=10, pady=10)


    def open(self):
        choose = Choose(self.update)

        
    def startday(self, month_clicked,year_clicked):
        data = calendar.monthrange(int(year_clicked), list(calendar.month_name).index(month_clicked))
        return data[0]+1
    


    def update(self, month_clicked,year_clicked):
        self.frame.destroy()
        #configure grid
        for rowcol in range(7):
            root.rowconfigure(rowcol, weight = 1)
            root.columnconfigure(rowcol, weight = 1)


        title_interchange =  month_clicked + ' ' + year_clicked


        #create widgets
        title_label = Label (root, text = title_interchange, font = ("Arial",14))

        Monday_label = Label (root, text = " Mo ")
        Tuesday_label = Label (root, text = " Tu ")
        Wednesday_label = Label (root, text = " We ")
        Thursday_label = Label (root, text = " Th ")
        Friday_label = Label (root, text = " Fr ")
        Saturday_label = Label (root, text = " Sa ")
        Sunday_label = Label (root, text = " Su ")

        one_button = Button (root, text = "    1    ")
        two_button = Button (root, text = "    2    ")
        three_button = Button (root, text = "    3    ")
        four_button = Button (root, text = "   4   ")
        five_button = Button (root, text = "    5    ")
        six_button = Button (root, text = "    6    ")
        seven_button = Button (root, text = "    7    ")
        eight_button = Button (root, text = "    8    ")
        nine_button = Button (root, text = "    9    ")
        ten_button = Button (root, text = "    10    ")
        eleven_button = Button (root, text = "    11    ")
        twelve_button = Button (root, text = "    12    ")
        thirteen_button = Button (root, text = "    13    ")
        fourteen_button = Button (root, text = "    14    ")
        fifteen_button = Button (root, text = "    15    ")
        sixteen_button = Button (root, text = "    16    ")
        seventeen_button = Button (root, text = "    17    ")
        eighteen_button = Button (root, text = "    18    ")
        nineteen_button = Button (root, text = "    19    ")
        twenty_button = Button (root, text = "    20    ")
        twentyone_button = Button (root, text = "    21    ")
        twentytwo_button = Button (root, text = "    22    ")
        twentythree_button = Button (root, text = "    23    ")
        twentyfour_button = Button (root, text = "    24    ")
        twentyfive_button = Button (root, text = "    25    ")
        twentysix_button = Button (root, text = "    26    ")
        twentyseven_button = Button (root, text = "    27    ")
        twentyeight_button = Button (root, text = "    28    ")
        twentynine_button = Button (root, text = "    29    ")
        thirty_button = Button (root, text = "    30    ")
        thirtyone_button = Button (root, text = "    31    ")


        # fake numbers
        fake_one_button = Button (root, text = "    1    ", fg = 'gray')
        fake_two_button = Button (root, text = "    2    ",fg='gray')
        fake_three_button = Button (root, text = "    3    ",fg='gray')
        fake_four_button = Button (root, text = "   4   ",fg='gray')
        fake_five_button = Button (root, text = "    5    ",fg='gray')
        fake_six_button = Button (root, text = "    6    ",fg='gray')

        fake_twentysix_button = Button (root, text = "    26    ",fg='gray')
        fake_twentyseven_button = Button (root, text = "    27    ",fg='gray')
        fake_twentyeight_button = Button (root, text = "    28    ",fg='gray')
        fake_twentynine_button = Button (root, text = "    29    ",fg='gray')
        fake_thirty_button = Button (root, text = "    30    ",fg = 'gray')
        fake_thirtyone_button = Button (root, text = "    31    ",fg = 'gray')





        title_label.grid (row=0, column=0, columnspan=7)

        Monday_label.grid (row=1, column=0)
        Tuesday_label.grid (row=1, column=1)
        Wednesday_label.grid (row=1, column=2)
        Thursday_label.grid (row=1, column=3)
        Friday_label.grid (row=1, column=4)
        Saturday_label.grid (row=1, column=5)
        Sunday_label.grid (row=1, column=6)

        #call startday

        day = self.startday(month_clicked,year_clicked)

        if day == 0:
            one_button.grid (row= 2, column=0)
            two_button.grid (row= 2, column=1)
            three_button.grid (row= 2, column=2)
            four_button.grid (row= 2, column=3)
            five_button.grid (row= 2, column=4)
            six_button.grid (row= 2, column=5)
            seven_button.grid (row= 2, column=6)
            eight_button.grid (row= 3, column=0)
            nine_button.grid (row= 3, column=1)
            ten_button.grid (row= 3, column=2)
            eleven_button.grid (row= 3, column=3)
            twelve_button.grid (row= 3, column=4)
            thirteen_button.grid (row= 3, column=5)
            fourteen_button.grid (row= 3, column=6)
            fifteen_button.grid (row= 4, column=0)
            sixteen_button.grid (row= 4, column=1)
            seventeen_button.grid (row= 4, column=2)
            eighteen_button.grid (row= 4, column=3)
            nineteen_button.grid (row= 4, column=4)
            twenty_button.grid (row= 4, column=5)
            twentyone_button.grid (row= 4, column=6)
            twentytwo_button.grid (row= 5, column=0)
            twentythree_button.grid (row= 5, column=1)
            twentyfour_button.grid (row= 5, column=2)
            twentyfive_button.grid (row= 5, column=3)
            twentysix_button.grid (row= 5, column=4)
            twentyseven_button.grid (row= 5, column=5)
            twentyeight_button.grid (row= 5, column=6)
            twentynine_button.grid (row= 6, column=0)
            thirty_button.grid (row= 6, column=1)
            thirtyone_button.grid (row= 6, column=2)
            fake_one_button.grid (row=6,column=3)
            fake_two_button.grid (row=6,column=4)
            fake_three_button.grid (row=6,column=5)
            fake_four_button.grid (row=6,column=6)

        if day == 1:
            fake_thirtyone_button.grid(row=2,column=0)
            one_button.grid (row= 2, column=1)
            two_button.grid (row= 2, column=2)
            three_button.grid (row= 2, column=3)
            four_button.grid (row= 2, column=4)
            five_button.grid (row= 2, column=5)
            six_button.grid (row= 2, column=6)
            seven_button.grid (row= 3, column=0)
            eight_button.grid (row= 3, column=1)
            nine_button.grid (row= 3, column=2)
            ten_button.grid (row= 3, column=3)
            eleven_button.grid (row= 3, column=4)
            twelve_button.grid (row= 3, column=5)
            thirteen_button.grid (row= 3, column=6)
            fourteen_button.grid (row= 4, column=0)
            fifteen_button.grid (row= 4, column=1)
            sixteen_button.grid (row= 4, column=2)
            seventeen_button.grid (row= 4, column=3)
            eighteen_button.grid (row= 4, column=4)
            nineteen_button.grid (row= 4, column=5)
            twenty_button.grid (row= 4, column=6)
            twentyone_button.grid (row= 5, column=0)
            twentytwo_button.grid (row= 5, column=1)
            twentythree_button.grid (row= 5, column=2)
            twentyfour_button.grid (row= 5, column=3)
            twentyfive_button.grid (row= 5, column=4)
            twentysix_button.grid (row= 5, column=5)
            twentyseven_button.grid (row= 5, column=6)
            twentyeight_button.grid (row= 6, column=0)
            twentynine_button.grid (row= 6, column=1)
            thirty_button.grid (row= 6, column=2)
            thirtyone_button.grid (row= 6, column=3)
            fake_one_button.grid (row=6,column=4)
            fake_two_button.grid (row=6,column=5)
            fake_three_button.grid (row=6,column=6)

        if day == 2:
            fake_thirty_button.grid(row=2,column=0)
            fake_thirtyone_button.grid(row=2,column=1)
            one_button.grid (row= 2, column=2)
            two_button.grid (row= 2, column=3)
            three_button.grid (row= 2, column=4)
            four_button.grid (row= 2, column=5)
            five_button.grid (row= 2, column=6)
            six_button.grid (row= 3, column=0)
            seven_button.grid (row= 3, column=1)
            eight_button.grid (row= 3, column=2)
            nine_button.grid (row= 3, column=3)
            ten_button.grid (row= 3, column=4)
            eleven_button.grid (row= 3, column=5)
            twelve_button.grid (row= 3, column=6)
            thirteen_button.grid (row= 4, column=0)
            fourteen_button.grid (row= 4, column=1)
            fifteen_button.grid (row= 4, column=2)
            sixteen_button.grid (row= 4, column=3)
            seventeen_button.grid (row= 4, column=4)
            eighteen_button.grid (row= 4, column=5)
            nineteen_button.grid (row= 4, column=6)
            twenty_button.grid (row= 5, column=0)
            twentyone_button.grid (row= 5, column=1)
            twentytwo_button.grid (row= 5, column=2)
            twentythree_button.grid (row= 5, column=3)
            twentyfour_button.grid (row= 5, column=4)
            twentyfive_button.grid (row= 5, column=5)
            twentysix_button.grid (row= 5, column=6)
            twentyseven_button.grid (row= 6, column=0)
            twentyeight_button.grid (row= 6, column=1)
            twentynine_button.grid (row= 6, column=2)
            thirty_button.grid (row= 6, column=3)
            thirtyone_button.grid (row= 6, column=4)
            fake_one_button.grid (row=6,column=5)
            fake_two_button.grid (row=6,column=6)

        if day == 3:
            fake_twentynine_button.grid(row=2,column=0)
            fake_thirty_button.grid(row=2,column=1)
            fake_thirtyone_button.grid(row=2,column=2)
            one_button.grid (row= 2, column=3)
            two_button.grid (row= 2, column=4)
            three_button.grid (row= 2, column=5)
            four_button.grid (row= 2, column=6)
            five_button.grid (row= 3, column=0)
            six_button.grid (row= 3, column=1)
            seven_button.grid (row= 3, column=2)
            eight_button.grid (row= 3, column=3)
            nine_button.grid (row= 3, column=4)
            ten_button.grid (row= 3, column=5)
            eleven_button.grid (row= 3, column=6)
            twelve_button.grid (row= 4, column=0)
            thirteen_button.grid (row= 4, column=1)
            fourteen_button.grid (row= 4, column=2)
            fifteen_button.grid (row= 4, column=3)
            sixteen_button.grid (row= 4, column=4)
            seventeen_button.grid (row= 4, column=5)
            eighteen_button.grid (row= 4, column=6)
            nineteen_button.grid (row= 5, column=0)
            twenty_button.grid (row= 5, column=1)
            twentyone_button.grid (row= 5, column=2)
            twentytwo_button.grid (row= 5, column=3)
            twentythree_button.grid (row= 5, column=4)
            twentyfour_button.grid (row= 5, column=5)
            twentyfive_button.grid (row= 5, column=6)
            twentysix_button.grid (row= 6, column=0)
            twentyseven_button.grid (row= 6, column=1)
            twentyeight_button.grid (row= 6, column=2)
            twentynine_button.grid (row= 6, column=3)
            thirty_button.grid (row= 6, column=4)
            thirtyone_button.grid (row= 6, column=5)
            fake_one_button.grid (row=6,column=6)

        if day == 4:
            fake_twentyeight_button.grid(row=2,column=0)
            fake_twentynine_button.grid(row=2,column=1)
            fake_thirty_button.grid(row=2,column=2)
            fake_thirtyone_button.grid(row=2,column=3)
            one_button.grid (row= 2, column=4)
            two_button.grid (row= 2, column=5)
            three_button.grid (row= 2, column=6)
            four_button.grid (row= 3, column=0)
            five_button.grid (row= 3, column=1)
            six_button.grid (row= 3, column=2)
            seven_button.grid (row= 3, column=3)
            eight_button.grid (row= 3, column=4)
            nine_button.grid (row= 3, column=5)
            ten_button.grid (row= 3, column=6)
            eleven_button.grid (row= 4, column=0)
            twelve_button.grid (row= 4, column=1)
            thirteen_button.grid (row= 4, column=2)
            fourteen_button.grid (row= 4, column=3)
            fifteen_button.grid (row= 4, column=4)
            sixteen_button.grid (row= 4, column=5)
            seventeen_button.grid (row= 4, column=6)
            eighteen_button.grid (row= 5, column=0)
            nineteen_button.grid (row= 5, column=1)
            twenty_button.grid (row= 5, column=2)
            twentyone_button.grid (row= 5, column=3)
            twentytwo_button.grid (row= 5, column=4)
            twentythree_button.grid (row= 5, column=5)
            twentyfour_button.grid (row= 5, column=6)
            twentyfive_button.grid (row= 6, column=0)
            twentysix_button.grid (row= 6, column=1)
            twentyseven_button.grid (row= 6, column=2)
            twentyeight_button.grid (row= 6, column=3)
            twentynine_button.grid (row= 6, column=4)
            thirty_button.grid (row= 6, column=5)
            thirtyone_button.grid (row= 6, column=6)

        if day == 5:
            fake_twentyseven_button.grid(row=2,column=0)
            fake_twentyeight_button.grid(row=2,column=1)
            fake_twentynine_button.grid(row=2,column=2)
            fake_thirty_button.grid(row=2,column=3)
            fake_thirtyone_button.grid(row=2,column=4)
            one_button.grid (row= 2, column=5)
            two_button.grid (row= 2, column=6)
            three_button.grid (row= 3, column=0)
            four_button.grid (row= 3, column=1)
            five_button.grid (row= 3, column=2)
            six_button.grid (row= 3, column=3)
            seven_button.grid (row= 3, column=4)
            eight_button.grid (row= 3, column=5)
            nine_button.grid (row= 3, column=6)
            ten_button.grid (row= 4, column=0)
            eleven_button.grid (row= 4, column=1)
            twelve_button.grid (row= 4, column=2)
            thirteen_button.grid (row= 4, column=3)
            fourteen_button.grid (row= 4, column=4)
            fifteen_button.grid (row= 4, column=5)
            sixteen_button.grid (row= 4, column=6)
            seventeen_button.grid (row= 5, column=0)
            eighteen_button.grid (row= 5, column=1)
            nineteen_button.grid (row= 5, column=2)
            twenty_button.grid (row= 5, column=3)
            twentyone_button.grid (row= 5, column=4)
            twentytwo_button.grid (row= 5, column=5)
            twentythree_button.grid (row= 5, column=6)
            twentyfour_button.grid (row= 6, column=0)
            twentyfive_button.grid (row= 6, column=1)
            twentysix_button.grid (row= 6, column=2)
            twentyseven_button.grid (row= 6, column=3)
            twentyeight_button.grid (row= 6, column=4)
            twentynine_button.grid (row= 6, column=5)
            thirty_button.grid (row= 6, column=6)
            thirtyone_button.grid (row= 7, column=0)
            fake_one_button.grid (row=7,column=1)
            fake_two_button.grid (row=7,column=2)
            fake_three_button.grid (row=7,column=3)
            fake_four_button.grid (row=7,column=4)
            fake_five_button.grid (row=7,column=5)
            fake_six_button.grid (row=7,column=6)


        if day == 6:
            fake_twentysix_button.grid(row=2,column=0)
            fake_twentyseven_button.grid(row=2,column=1)
            fake_twentyeight_button.grid(row=2,column=2)
            fake_twentynine_button.grid(row=2,column=3)
            fake_thirty_button.grid(row=2,column=4)
            fake_thirtyone_button.grid(row=2,column=5)
            one_button.grid (row= 2, column=6)
            two_button.grid (row= 3, column=0)
            three_button.grid (row= 3, column=1)
            four_button.grid (row= 3, column=2)
            five_button.grid (row= 3, column=3)
            six_button.grid (row= 3, column=4)
            seven_button.grid (row= 3, column=5)
            eight_button.grid (row= 3, column=6)
            nine_button.grid (row= 4, column=0)
            ten_button.grid (row= 4, column=1)
            eleven_button.grid (row= 4, column=2)
            twelve_button.grid (row= 4, column=3)
            thirteen_button.grid (row= 4, column=4)
            fourteen_button.grid (row= 4, column=5)
            fifteen_button.grid (row= 4, column=6)
            sixteen_button.grid (row= 5, column=0)
            seventeen_button.grid (row= 5, column=1)
            eighteen_button.grid (row= 5, column=2)
            nineteen_button.grid (row= 5, column=3)
            twenty_button.grid (row= 5, column=4)
            twentyone_button.grid (row= 5, column=5)
            twentytwo_button.grid (row= 5, column=6)
            twentythree_button.grid (row= 6, column=0)
            twentyfour_button.grid (row= 6, column=1)
            twentyfive_button.grid (row= 6, column=2)
            twentysix_button.grid (row= 6, column=3)
            twentyseven_button.grid (row= 6, column=4)
            twentyeight_button.grid (row= 6, column=5)
            twentynine_button.grid (row= 6, column=6)
            thirty_button.grid (row= 7, column=0)
            thirtyone_button.grid (row= 7, column=1)
            fake_one_button.grid (row=7,column=2)
            fake_two_button.grid (row=7,column=3)
            fake_three_button.grid (row=7,column=4)
            fake_four_button.grid (row=7,column=5)
            fake_five_button.grid (row=7,column=6)


class Choose:
    def __init__(self, update):
        top = Toplevel()
        self.frame = Frame(top)
        self.update = update
        

        top.title("Choose")
        top.resizable(True, True)

        #put dropbox etc right here
        month_label = Label(top,  text = 'Choose month:').pack(padx=10,pady=30)
        self.month_clicked = StringVar()
        month_dropdown = ttk.Combobox(top, width = 27, textvariable = self.month_clicked)
        month_dropdown['values'] = ('January','February','March','April','May','June','July','August','September','October', 'November','December')
        month_dropdown.pack(padx=10,pady=30)

        year_label = Label(top,  text = 'Choose year:').pack(padx=10,pady=30)
        self.year_clicked = StringVar()
        year_dropdown = ttk.Combobox(top, width = 27, textvariable = self.year_clicked)
        year_dropdown['values']  = ('2024','2025','2026','2027')
        year_dropdown.pack(padx=10,pady=30)

        save_button = Button(top,  text = 'Save', command = self.submit)
        save_button.pack(padx=10,pady=30)

        self.frame.pack(padx=10, pady=10)

    def submit(self):
        self.update(self.month_clicked.get(), self.year_clicked.get())


root = Tk()
root.title("Calender")
root.resizable(True, True)
calender = Calender(root)
root.mainloop()



    


